apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: brewery-discovery
    labels:
      app: brewery-discovery
  spec:
    ports:
    - port: 8761
      targetPort: 8761
    selector:
      deploymentconfig: brewery-discovery
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: brewery-discovery
    name: brewery-discovery
  spec:
    replicas: 1
    selector:
      deploymentconfig: brewery-discovery
    template:
      metadata:
        labels:
          deploymentconfig: brewery-discovery
      spec:
        containers:
        - image: yanaga/brewery-discovery:latest
          name: brewery-discovery
          ports:
          - containerPort: 8761
            protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8761
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 0
            successThreshold: 1
            timeoutSeconds: 1
- apiVersion: v1
  kind: Route
  metadata:
    name: brewery-discovery
    labels:
      app: brewery-discovery
  spec:
    to:
      kind: Service
      name: brewery-discovery
