logging.file: build/config-server.log

server.port: ${PORT:8888}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yanaga/brewery-config.git

spring.zipkin.enabled: false


endpoints.health.sensitive: false